"""HTML/CSS template defaults used by the generator."""
DEFAULT_BASE_HTML = '''<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ project_name|default:"My Django Project" }}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header class="site-header">
      <div class="container nav-wrap">
        <div class="brand">{{ title|default:"My Django Project" }}</div>
        <nav class="nav">
          <a class="nav-link" href="/">Home</a>
          {% if apps %}
            {% for app in apps %}
              <a class="nav-link" href="/{{ app }}/">{{ app|title }}</a>
            {% endfor %}
          {% endif %}
        </nav>
      </div>
    </header>

    <main class="site-main container">
      {% block content %}{% endblock %}
    </main>

    <footer class="site-footer">
      <div class="container">© {{ now|date:"Y" }} — Generated by Django Bootstrapper</div>
    </footer>
  </body>
</html>'''

DEFAULT_HOME_HTML = '''{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="card" style="text-align:center; padding:2rem;">
    <h2>Welcome to {{ project_name|title }}</h2>
    <p>Your Django project has been generated successfully.</p>
    <p>Use the navigation bar above to open any app.</p>
  </div>
{% endblock %}'''

DEFAULT_APP_INDEX_HTML = '''{% extends 'base.html' %}
{% block content %}
  <div class="card">
    <h2>{{ app_title }}</h2>
    <p>This page was generated for this app module.</p>
    <p>You can edit <code>templates/app_index.html</code> to customize all new app pages.</p>
  </div>
{% endblock %}'''

DEFAULT_CSS = '''/* Modern dark theme for generated projects */
:root{
  --bg:#0f1720;
  --surface:#0b1220;
  --muted:#9aa4b2;
  --accent:#7c3aed;
  --accent-2:#06b6d4;
  --card:#0b1220;
  --radius:10px;
}
*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0;
  font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial;
  background:linear-gradient(180deg,var(--bg),#071018);
  color:#e6eef6;
  -webkit-font-smoothing:antialiased;
}
.container{max-width:1100px;margin:0 auto;padding:18px}
.site-header{background:linear-gradient(90deg,rgba(255,255,255,0.02),rgba(255,255,255,0.01));border-bottom:1px solid rgba(255,255,255,0.03);}
.nav-wrap{display:flex;align-items:center;gap:18px;justify-content:space-between;}
.brand{font-weight:700;font-size:1.15rem;color:var(--accent);}
.nav{display:flex;gap:10px;align-items:center}
.nav-link{color:var(--muted);text-decoration:none;padding:8px 12px;border-radius:8px;transition:all .15s}
.nav-link:hover{color:#fff;background:rgba(255,255,255,0.02);transform:translateY(-1px)}
.site-main{padding:28px}
.card{background:linear-gradient(180deg,rgba(255,255,255,0.02),rgba(255,255,255,0.01));border-radius:var(--radius);padding:18px;border:1px solid rgba(255,255,255,0.03);box-shadow:0 6px 18px rgba(2,6,23,0.6)}
h1,h2{margin:0 0 8px 0;color:#eaf2ff}
.muted{color:var(--muted)}
.btn{display:inline-block;padding:10px 14px;border-radius:8px;background:linear-gradient(180deg,var(--accent),#5b21b6);color:white;text-decoration:none}
.site-footer{padding:18px;border-top:1px solid rgba(255,255,255,0.03);text-align:center;color:var(--muted)}

/* responsive */
@media (max-width:720px){
  .nav{display:flex;flex-wrap:wrap;gap:6px}
  .nav-wrap{flex-direction:column;align-items:flex-start}
}
'''
